### PR TITLE
Add Steam, Snapchat & YouTube tiles.

### PR DESCRIPTION
**Pull request by filfat**

### CODE REVIEW

**Comment by SniperGER** [comment]
The Steam icon doesn't really look like the current actual Steam icon, not to mention some of the circles are way off. You might consider using an SVG variant of the current icon instead.

https://upload.wikimedia.org/wikipedia/commons/8/83/Steam_icon_logo.svg

**Comment by filfat** [comment]
That one uses color; I can remove the steam tile till we support color?

**Comment by filfat** [comment]
Done

**Comment by SniperGER** [comment]
Modified the SVG from Wikipedia so it doesn't have color (and the white parts are cut out instead of just being white). The other two tiles good the way they are.

**Pull request merged**
